title: "Xeph's Home"
description: "Musings, stories, research and everything in between."
url: "https://xepherra.github.io"
baseurl: ""

exclude:
  - .devcontainer

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

collections:
  stories:
    output: true
    permalink: /stories/:name/

# Defaults
defaults:
  # Turn off author card site-wide (covers pages like index/about/blog)
  - scope:
      path: ""
    values:
      author_profile: false

  # Posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: false

  # Stories (collection)
  - scope:
      path: ""
      type: "stories"
    values:
      layout: single
      author_profile: false

# If you want pagination on the HOME page, keep this:
paginate: 5
paginate_path: "/page:num/"
# If you prefer pagination on /blog/, note: the built-in paginator only paginates the root index.
# In that case, remove 'paginate' and 'paginate_path' entirely and use /blog/ as a non-paginated archive.

author:
  name: "Firas"
  bio: "Sci-fi short stories and thought experiments."
